### ISSUE TITLE
Can't install from pip

### ISSUE THREAD

**Issue by koddr** [kakwa/py-ascii-graph#17]
Hello.

Python 3.6.3, macOS 10.13. 

I can't install your package from pip. I use `pip install ascii_graph` and see this error message:

```bash
Collecting ascii_graph
  Using cached ascii_graph-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sb/pctpc4n106j0gncbjwvg9p7m0000gn/T/pycharm-packaging/ascii-graph/setup.py", line 9, in <module>
        description = f.read()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2269: ordinal not in range(128)
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/pctpc4n106j0gncbjwvg9p7m0000gn/T/pycharm-packaging/ascii-graph/
```
How to solve this?
Thanks.

**Comment by kakwa** [comment]
Hello,

I've uploaded a new version with some fixed in setup.py (specification of the encoding when reading LICENSE and README.rst + safe  fallback in case of error as these items are mostly cosmetic).

the ```pip install``` should work now.

**Comment by koddr** [comment]
Oh, thanks! It's working now. 👍
